CAT_EVAL: false
CUDA_VISIBLE_DEVICES: 0,1,2,3
DEBUG: false
DEBUG_DIR: /debug_logs
DataParallel: false
Feat_Filter: false
Fix_Visual: false
LOG4TEST: false
Return_B4_BN: false
al: 1.0
alpha: 0.9
auto_resume_training_from_lastest_step: false
batch_size: 32
beta: 0.999
captioner_name: Blip
checkpoint_epoch: 10
classifier_lr_factor: 2.0
cmm_loss_weight: 1.0
cmt_depth: 1
config_select: default
cuda: cuda
dataset: sysu
eval_epoch: 2
eval_num_regdb: 1
eval_start_epoch: 80
focal_three_fusion_loss: false
focal_three_fusion_loss2: false
focal_three_fusion_loss3: false
focal_three_fusion_loss4: false
focal_three_fusion_loss5: false
focal_three_fusion_loss6: false
focalthree_four_fusion_loss: false
focalthree_fusion_loss: false
four_fusion_loss: false
fusion_way: add
ga: 2.0
gall_mode: single
gamma: 0.1
gpu_id: '0'
id_loss_weight: 1.0
img_h: 288
img_size: !!python/tuple
- 288
- 144
img_w: 144
joint_mode: ir_crossfusion
klp: 1.0
label_mix: false
learnable_loss_weight: false
llcm_data_path: datasets/llcm
llm_aug: false
llm_aug_prob: 0.5
loss_names: wrt,id
lr_factor: 5.0
lr_txt: 1.0e-05
lr_visual: 0.00035
lrscheduler: step
max_save_model_num: 1
milestones: !!python/tuple
- 40
- 60
- 100
mode: train
momentum: 0.9
num_pos: 4
num_workers: 8
only_fusion_loss: false
only_sketch: false
only_text: false
optimizer: Adam
output_path: logs/
pa: 0.1
pid_num: 395
pooling: GEM
power: 0.9
pretrain_choice: RN50_ORI
pretrain_path: default
prj_output_dim: 2048
regdb_data_path: datasets/regdb
regdb_test_mode: t-v
resume_test_model: -1
resume_train_epoch: -1
seed: 1
stride_size: 16
sysu_data_path: datasets/sysu
target_lr: 0.0
temperature: 0.07
test_modality: Fusion
test_mode: all
test_model_path: null
test_model_type: Fusion
text_bias_lr_factor: 2.0
text_length: 77
text_weight_decay: 4.0e-05
text_weight_decay_bias: 0.0
total_train_epoch: 120
training_mode: RGB_IR_Text
training_weight_init: null
trial: 1
uni_BN: false
visual_bias_lr_factor: 1.0
visual_weight_decay: 0.0005
visual_weight_decay_bias: 0.0005
vocab_size: 49408
warmup_epochs: 10
warmup_factor: 0.01
warmup_method: linear
wrt_loss_weight: 1.0
